// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NomadLife.Web.Data;

#nullable disable

namespace NomadLife.Web.Data.Migrations
{
    [DbContext(typeof(HotelContext))]
    partial class HotelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NomadLife.Web.Data.Entities.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Paweł Syrowy",
                            Slug = "pawel-syrowy"
                        });
                });

            modelBuilder.Entity("NomadLife.Web.Data.Entities.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("BuyLink")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(180)
                        .IsUnicode(false)
                        .HasColumnType("varchar(180)");

                    b.Property<int>("NumStars")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .IsUnicode(false)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "A serene retreat located on the shores of a pristine beach, offering breathtaking ocean views and luxurious amenities.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel1.jpg",
                            NumStars = 5,
                            Title = "Ocean Breeze Hotel",
                            Type = "Hotel"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "A cozy and affordable hostel nestled in the heart of the mountains, perfect for backpackers and nature lovers.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel2.jpg",
                            NumStars = 3,
                            Title = "Mountain View Hostel",
                            Type = "Hostel"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 1,
                            Description = "A modern and stylish apartment located in the bustling city center, ideal for business travelers and tourists.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel3.jpg",
                            NumStars = 4,
                            Title = "City Central Apartment",
                            Type = "Apartment"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 1,
                            Description = "A charming inn situated by the river, offering a peaceful and relaxing atmosphere with scenic views.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel4.jpg",
                            NumStars = 4,
                            Title = "Riverside Inn",
                            Type = "Hotel"
                        },
                        new
                        {
                            Id = 5,
                            AuthorId = 1,
                            Description = "An exotic resort located in the middle of the desert, providing luxurious accommodations and unique experiences.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel5.jpg",
                            NumStars = 5,
                            Title = "Desert Oasis Resort",
                            Type = "Resort"
                        },
                        new
                        {
                            Id = 6,
                            AuthorId = 1,
                            Description = "A quaint bed and breakfast in a historic downtown area, featuring cozy rooms and homemade breakfast.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel6.jpg",
                            NumStars = 3,
                            Title = "Historic Downtown Bed & Breakfast",
                            Type = "Bed & Breakfast"
                        },
                        new
                        {
                            Id = 7,
                            AuthorId = 1,
                            Description = "A rustic lodge located by the lake, offering a perfect getaway for fishing, boating, and relaxation.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel7.jpg",
                            NumStars = 4,
                            Title = "Lakeside Lodge",
                            Type = "Lodge"
                        },
                        new
                        {
                            Id = 8,
                            AuthorId = 1,
                            Description = "A trendy boutique hotel in the heart of the city, known for its stylish design and personalized service.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel8.jpg",
                            NumStars = 5,
                            Title = "Urban Chic Boutique Hotel",
                            Type = "Boutique Hotel"
                        },
                        new
                        {
                            Id = 9,
                            AuthorId = 1,
                            Description = "An environmentally friendly retreat offering sustainable accommodations and activities in nature.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel9.jpg",
                            NumStars = 4,
                            Title = "Eco-Friendly Retreat",
                            Type = "Retreat"
                        },
                        new
                        {
                            Id = 10,
                            AuthorId = 1,
                            Description = "A welcoming guesthouse located in the tranquil countryside, perfect for a peaceful escape from the city.",
                            Image = "https://raw.github.com/PawelSyrowy/NomadLifeImages/main/hotel10.jpg",
                            NumStars = 3,
                            Title = "Countryside Guesthouse",
                            Type = "Guesthouse"
                        });
                });

            modelBuilder.Entity("NomadLife.Web.Data.Entities.Location", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("Id"));

                    b.Property<bool>("IsTop")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(75)
                        .IsUnicode(false)
                        .HasColumnType("varchar(75)");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = (short)1,
                            IsTop = true,
                            Name = "United States",
                            Slug = "united-states"
                        },
                        new
                        {
                            Id = (short)2,
                            IsTop = true,
                            Name = "France",
                            Slug = "france"
                        },
                        new
                        {
                            Id = (short)3,
                            IsTop = true,
                            Name = "Italy",
                            Slug = "italy"
                        },
                        new
                        {
                            Id = (short)4,
                            IsTop = false,
                            Name = "Spain",
                            Slug = "spain"
                        },
                        new
                        {
                            Id = (short)5,
                            IsTop = true,
                            Name = "United Kingdom",
                            Slug = "united-kingdom"
                        },
                        new
                        {
                            Id = (short)6,
                            IsTop = false,
                            Name = "Mexico",
                            Slug = "mexico"
                        },
                        new
                        {
                            Id = (short)7,
                            IsTop = false,
                            Name = "Germany",
                            Slug = "germany"
                        },
                        new
                        {
                            Id = (short)8,
                            IsTop = false,
                            Name = "Thailand",
                            Slug = "thailand"
                        },
                        new
                        {
                            Id = (short)9,
                            IsTop = false,
                            Name = "China",
                            Slug = "china"
                        },
                        new
                        {
                            Id = (short)10,
                            IsTop = true,
                            Name = "Japan",
                            Slug = "japan"
                        },
                        new
                        {
                            Id = (short)11,
                            IsTop = false,
                            Name = "Turkey",
                            Slug = "turkey"
                        },
                        new
                        {
                            Id = (short)12,
                            IsTop = false,
                            Name = "Greece",
                            Slug = "greece"
                        },
                        new
                        {
                            Id = (short)13,
                            IsTop = false,
                            Name = "Canada",
                            Slug = "canada"
                        },
                        new
                        {
                            Id = (short)14,
                            IsTop = false,
                            Name = "Australia",
                            Slug = "australia"
                        },
                        new
                        {
                            Id = (short)15,
                            IsTop = false,
                            Name = "Brazil",
                            Slug = "brazil"
                        },
                        new
                        {
                            Id = (short)16,
                            IsTop = false,
                            Name = "Argentina",
                            Slug = "argentina"
                        },
                        new
                        {
                            Id = (short)17,
                            IsTop = false,
                            Name = "South Korea",
                            Slug = "south-korea"
                        },
                        new
                        {
                            Id = (short)18,
                            IsTop = false,
                            Name = "Egypt",
                            Slug = "egypt"
                        },
                        new
                        {
                            Id = (short)19,
                            IsTop = false,
                            Name = "South Africa",
                            Slug = "south-africa"
                        },
                        new
                        {
                            Id = (short)20,
                            IsTop = true,
                            Name = "India",
                            Slug = "india"
                        },
                        new
                        {
                            Id = (short)21,
                            IsTop = false,
                            Name = "Russia",
                            Slug = "russia"
                        },
                        new
                        {
                            Id = (short)22,
                            IsTop = false,
                            Name = "Indonesia",
                            Slug = "indonesia"
                        },
                        new
                        {
                            Id = (short)23,
                            IsTop = false,
                            Name = "Vietnam",
                            Slug = "vietnam"
                        },
                        new
                        {
                            Id = (short)24,
                            IsTop = false,
                            Name = "Netherlands",
                            Slug = "netherlands"
                        },
                        new
                        {
                            Id = (short)25,
                            IsTop = false,
                            Name = "Malaysia",
                            Slug = "malaysia"
                        },
                        new
                        {
                            Id = (short)26,
                            IsTop = false,
                            Name = "Switzerland",
                            Slug = "switzerland"
                        },
                        new
                        {
                            Id = (short)27,
                            IsTop = true,
                            Name = "Portugal",
                            Slug = "portugal"
                        },
                        new
                        {
                            Id = (short)28,
                            IsTop = false,
                            Name = "New Zealand",
                            Slug = "new-zealand"
                        },
                        new
                        {
                            Id = (short)29,
                            IsTop = false,
                            Name = "Austria",
                            Slug = "austria"
                        },
                        new
                        {
                            Id = (short)30,
                            IsTop = false,
                            Name = "Sweden",
                            Slug = "sweden"
                        },
                        new
                        {
                            Id = (short)31,
                            IsTop = false,
                            Name = "Norway",
                            Slug = "norway"
                        },
                        new
                        {
                            Id = (short)32,
                            IsTop = false,
                            Name = "Denmark",
                            Slug = "denmark"
                        },
                        new
                        {
                            Id = (short)33,
                            IsTop = false,
                            Name = "Finland",
                            Slug = "finland"
                        },
                        new
                        {
                            Id = (short)34,
                            IsTop = false,
                            Name = "Belgium",
                            Slug = "belgium"
                        },
                        new
                        {
                            Id = (short)35,
                            IsTop = false,
                            Name = "Ireland",
                            Slug = "ireland"
                        },
                        new
                        {
                            Id = (short)36,
                            IsTop = false,
                            Name = "Scotland",
                            Slug = "scotland"
                        },
                        new
                        {
                            Id = (short)37,
                            IsTop = false,
                            Name = "Iceland",
                            Slug = "iceland"
                        },
                        new
                        {
                            Id = (short)38,
                            IsTop = false,
                            Name = "Croatia",
                            Slug = "croatia"
                        },
                        new
                        {
                            Id = (short)39,
                            IsTop = false,
                            Name = "Czech Republic",
                            Slug = "czech-republic"
                        },
                        new
                        {
                            Id = (short)40,
                            IsTop = false,
                            Name = "Hungary",
                            Slug = "hungary"
                        },
                        new
                        {
                            Id = (short)41,
                            IsTop = false,
                            Name = "Poland",
                            Slug = "poland"
                        },
                        new
                        {
                            Id = (short)42,
                            IsTop = false,
                            Name = "Israel",
                            Slug = "israel"
                        },
                        new
                        {
                            Id = (short)43,
                            IsTop = false,
                            Name = "Chile",
                            Slug = "chile"
                        },
                        new
                        {
                            Id = (short)44,
                            IsTop = false,
                            Name = "Peru",
                            Slug = "peru"
                        },
                        new
                        {
                            Id = (short)45,
                            IsTop = false,
                            Name = "Colombia",
                            Slug = "colombia"
                        },
                        new
                        {
                            Id = (short)46,
                            IsTop = true,
                            Name = "Singapore",
                            Slug = "singapore"
                        },
                        new
                        {
                            Id = (short)47,
                            IsTop = false,
                            Name = "Philippines",
                            Slug = "philippines"
                        },
                        new
                        {
                            Id = (short)48,
                            IsTop = false,
                            Name = "Morocco",
                            Slug = "morocco"
                        },
                        new
                        {
                            Id = (short)49,
                            IsTop = false,
                            Name = "United Arab Emirates",
                            Slug = "uae"
                        },
                        new
                        {
                            Id = (short)50,
                            IsTop = false,
                            Name = "Saudi Arabia",
                            Slug = "saudi-arabia"
                        },
                        new
                        {
                            Id = (short)51,
                            IsTop = false,
                            Name = "Qatar",
                            Slug = "qatar"
                        },
                        new
                        {
                            Id = (short)52,
                            IsTop = false,
                            Name = "Kuwait",
                            Slug = "kuwait"
                        },
                        new
                        {
                            Id = (short)53,
                            IsTop = false,
                            Name = "Jordan",
                            Slug = "jordan"
                        },
                        new
                        {
                            Id = (short)54,
                            IsTop = false,
                            Name = "Lebanon",
                            Slug = "lebanon"
                        },
                        new
                        {
                            Id = (short)55,
                            IsTop = false,
                            Name = "Nepal",
                            Slug = "nepal"
                        },
                        new
                        {
                            Id = (short)56,
                            IsTop = false,
                            Name = "Sri Lanka",
                            Slug = "sri-lanka"
                        },
                        new
                        {
                            Id = (short)57,
                            IsTop = false,
                            Name = "Bangladesh",
                            Slug = "bangladesh"
                        },
                        new
                        {
                            Id = (short)58,
                            IsTop = false,
                            Name = "Pakistan",
                            Slug = "pakistan"
                        },
                        new
                        {
                            Id = (short)59,
                            IsTop = false,
                            Name = "Myanmar",
                            Slug = "myanmar"
                        },
                        new
                        {
                            Id = (short)60,
                            IsTop = false,
                            Name = "Laos",
                            Slug = "laos"
                        },
                        new
                        {
                            Id = (short)61,
                            IsTop = false,
                            Name = "Cambodia",
                            Slug = "cambodia"
                        },
                        new
                        {
                            Id = (short)62,
                            IsTop = false,
                            Name = "Mongolia",
                            Slug = "mongolia"
                        },
                        new
                        {
                            Id = (short)63,
                            IsTop = false,
                            Name = "Kazakhstan",
                            Slug = "kazakhstan"
                        },
                        new
                        {
                            Id = (short)64,
                            IsTop = false,
                            Name = "Uzbekistan",
                            Slug = "uzbekistan"
                        },
                        new
                        {
                            Id = (short)65,
                            IsTop = false,
                            Name = "Romania",
                            Slug = "romania"
                        },
                        new
                        {
                            Id = (short)66,
                            IsTop = false,
                            Name = "Bulgaria",
                            Slug = "bulgaria"
                        },
                        new
                        {
                            Id = (short)67,
                            IsTop = false,
                            Name = "Ukraine",
                            Slug = "ukraine"
                        },
                        new
                        {
                            Id = (short)68,
                            IsTop = false,
                            Name = "Belarus",
                            Slug = "belarus"
                        },
                        new
                        {
                            Id = (short)69,
                            IsTop = false,
                            Name = "Estonia",
                            Slug = "estonia"
                        },
                        new
                        {
                            Id = (short)70,
                            IsTop = false,
                            Name = "Latvia",
                            Slug = "latvia"
                        },
                        new
                        {
                            Id = (short)71,
                            IsTop = false,
                            Name = "Lithuania",
                            Slug = "lithuania"
                        },
                        new
                        {
                            Id = (short)72,
                            IsTop = false,
                            Name = "Slovenia",
                            Slug = "slovenia"
                        },
                        new
                        {
                            Id = (short)73,
                            IsTop = false,
                            Name = "Slovakia",
                            Slug = "slovakia"
                        },
                        new
                        {
                            Id = (short)74,
                            IsTop = false,
                            Name = "Serbia",
                            Slug = "serbia"
                        });
                });

            modelBuilder.Entity("NomadLife.Web.Data.Entities.LocationHotels", b =>
                {
                    b.Property<short>("LocationId")
                        .HasColumnType("smallint");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.HasKey("LocationId", "HotelId");

                    b.HasIndex("HotelId");

                    b.ToTable("LocationHotels");

                    b.HasData(
                        new
                        {
                            LocationId = (short)15,
                            HotelId = 1
                        },
                        new
                        {
                            LocationId = (short)26,
                            HotelId = 2
                        },
                        new
                        {
                            LocationId = (short)7,
                            HotelId = 3
                        },
                        new
                        {
                            LocationId = (short)2,
                            HotelId = 4
                        },
                        new
                        {
                            LocationId = (short)48,
                            HotelId = 5
                        },
                        new
                        {
                            LocationId = (short)1,
                            HotelId = 6
                        },
                        new
                        {
                            LocationId = (short)13,
                            HotelId = 7
                        },
                        new
                        {
                            LocationId = (short)10,
                            HotelId = 8
                        },
                        new
                        {
                            LocationId = (short)28,
                            HotelId = 9
                        },
                        new
                        {
                            LocationId = (short)14,
                            HotelId = 10
                        });
                });

            modelBuilder.Entity("NomadLife.Web.Data.Entities.Hotel", b =>
                {
                    b.HasOne("NomadLife.Web.Data.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("NomadLife.Web.Data.Entities.LocationHotels", b =>
                {
                    b.HasOne("NomadLife.Web.Data.Entities.Hotel", "Hotel")
                        .WithMany("HotelLocations")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NomadLife.Web.Data.Entities.Location", "Location")
                        .WithMany("LocationHotels")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("NomadLife.Web.Data.Entities.Hotel", b =>
                {
                    b.Navigation("HotelLocations");
                });

            modelBuilder.Entity("NomadLife.Web.Data.Entities.Location", b =>
                {
                    b.Navigation("LocationHotels");
                });
#pragma warning restore 612, 618
        }
    }
}
